version: 0.0
os: linux
phases:
    install:
        commands:
        # Download and Install NodeJS 8.0     
        - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
        - sudo apt-get install -y nodejs
        - echo Installing source NPM dependencies...
        # Install http drivers for node
        - sudo apt-get update -y
        - sudo apt-get install -y apt-transport-https
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}
    post_build:
         commands:
            - aws s3 cp dist s3://${S3_BUCKET}/${StarWarsApp} --recursive
            - aws s3 cp appspec.yml s3://${S3_BUCKET} 
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
        - 'dist'
    #base-directory: 'dist*'
    discard-paths: no
